---
- name: Set up Debian Home Lab
  hosts: debian_server
  become: yes
  vars:
    dockge_version: "latest"
    jellyfin_version: "latest"
  vars_files:
    - vault.yml  # This file will contain encrypted sensitive data

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
          - python3-pip
        state: present

    - name: Create Dockge directory
      file:
        path: /opt/dockge
        state: directory

    - name: Deploy Dockge
      community.docker.docker_container:
        name: dockge
        image: "louislam/dockge:{{ dockge_version }}"
        state: started
        restart_policy: always
        ports:
          - "5001:5001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /opt/dockge:/app/data

    - name: Deploy Jellyfin
      community.docker.docker_container:
        name: jellyfin
        image: "jellyfin/jellyfin:{{ jellyfin_version }}"
        state: started
        restart_policy: always
        ports:
          - "8096:8096"
        volumes:
          - /path/to/jellyfin/config:/config
          - /path/to/jellyfin/cache:/cache
          - /path/to/media:/media

    # - name: Deploy Firefly III
    #   community.docker.docker_container:
    #     name: firefly-iii
    #     image: "fireflyiii/core:latest"
    #     state: started
    #     restart_policy: always
    #     ports:
    #       - "8080:8080"
    #     env:
    #       APP_KEY: "{{ firefly_app_key }}"
    #       DB_HOST: "{{ firefly_db_host }}"
    #       DB_PORT: "{{ firefly_db_port }}"
    #       DB_CONNECTION: "{{ firefly_db_connection }}"
    #       DB_DATABASE: "{{ firefly_db_name }}"
    #       DB_USERNAME: "{{ firefly_db_user }}"
    #       DB_PASSWORD: "{{ firefly_db_password }}"
    #     volumes:
    #       - /path/to/firefly/upload:/var/www/html/storage/upload
