---
- name: Create Docker network for Firefly III
  community.docker.docker_network:
    name: firefly_network
    state: present

- name: Deploy MariaDB for Firefly III
  community.docker.docker_container:
    name: firefly-db
    image: "mariadb:{{ mariadb_version }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: firefly_network
    env:
      MYSQL_ROOT_PASSWORD: "{{ mariadb_root_password }}"
      MYSQL_DATABASE: "{{ firefly_db_name }}"
      MYSQL_USER: "{{ firefly_db_user }}"
      MYSQL_PASSWORD: "{{ firefly_db_password }}"
    volumes:
      - "{{ docker_base_path }}/mariadb:/var/lib/mysql"
  tags:
    - finance
    - firefly
    - database

- name: Deploy Firefly III
  community.docker.docker_container:
    name: firefly-iii
    image: "fireflyiii/core:{{ firefly_version }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: firefly_network
    ports:
      - "8080:8080"
    env:
      APP_KEY: "{{ firefly_app_key }}"
      DB_HOST: "firefly-db"
      DB_PORT: "3306"
      DB_CONNECTION: "mysql"
      DB_DATABASE: "{{ firefly_db_name }}"
      DB_USERNAME: "{{ firefly_db_user }}"
      DB_PASSWORD: "{{ firefly_db_password }}"
    volumes:
      - "{{ docker_base_path }}/firefly/upload:/var/www/html/storage/upload"
  tags:
    - finance
    - firefly
