---
- name: Deploy Firefly III
  community.docker.docker_container:
    name: firefly-iii
    image: "fireflyiii/core:{{ firefly_version }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "8080:8080"
    env:
      APP_KEY: "{{ firefly_app_key }}"
      DB_HOST: "{{ firefly_db_host }}"
      DB_PORT: "{{ firefly_db_port }}"
      DB_CONNECTION: "{{ firefly_db_connection }}"
      DB_DATABASE: "{{ firefly_db_name }}"
      DB_USERNAME: "{{ firefly_db_user }}"
      DB_PASSWORD: "{{ firefly_db_password }}"
    volumes:
      - "{{ docker_base_path }}/firefly/upload:/var/www/html/storage/upload"
  tags:
    - finance
    - firefly
