---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: "yes"
    update_cache: true
  tags:
    - system
    - update

- name: Install required packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: present
  tags:
    - system
    - docker
