---
- name: Deploy qbittorrent
  community.docker.docker_container:
    name: qbittorrent
    image: "linuxserver/qbittorrent:{{ qbittorrent_version }}"
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      WEBUI_PORT: "8090"
    ports:
      - "8090:8090"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - "{{ docker_base_path }}/qbittorrent/config:/config"
      - "{{ docker_base_path }}/qbittorrent/downloads:/downloads"
    network_mode: container:wireguard
  tags:
    - qbittorrent
    - torrent
