---
- name: Deploy WireGuard Easy
  community.docker.docker_container:
    name: wg-easy
    image: "weejewel/wg-easy:{{ wg_easy_version }}"
    state: started
    restart_policy: unless-stopped
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    env:
      - WG_HOST={{ wireguard_host }}
      - PASSWORD={{ wireguard_password }}
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    sysctls:
      "net.ipv4.ip_forward": "1"
      "net.ipv4.conf.all.src_valid_mark": "1"
    volumes:
      - "{{ docker_base_path }}/wireguard/config:/etc/wireguard"
  tags:
    - vpn
    - wireguard
