---
# WireGuard server
- name: Deploy WireGuard Easy
  community.docker.docker_container:
    name: wg-easy
    image: "ghcr.io/wg-easy/wg-easy:{{ wg_easy_version }}"
    state: started
    restart_policy: unless-stopped
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    env:
      WG_HOST: "{{ wireguard_host }}"
      PASSWORD_HASH: "{{ wireguard_password }}"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    sysctls:
      "net.ipv4.ip_forward": "1"
      "net.ipv4.conf.all.src_valid_mark": "1"
    volumes:
      - "{{ docker_base_path }}/wireguard/config:/etc/wireguard"
  tags:
    - vpn
    - wg-easy

# WireGuard client
- name: Deploy WireGuard
  community.docker.docker_container:
    name: wireguard
    image: "linuxserver/wireguard:{{ wireguard_version }}"
    state: started
    restart_policy: unless-stopped
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    ports:
      - "51822:51820/udp"
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
    volumes:
      - "{{ docker_base_path }}/wireguard/config:/config"
      - "/lib/modules:/lib/modules:ro"
  tags:
    - vpn
    - wireguard
